version: '3.1'

services:
  blog_odopeyone_xyz:
    image: johnyserpa/odopeyone_blog
    build: .
    networks:
      - web
    environment:
      url: 'https://blog.dev.odopeyone.xyz'
    volumes:
      - $HOME/odopeyone_blog/content:/var/lib/ghost/content

networks:
  web:
    external:
      name: web-server
